# Change these first
owner: Leies-202 # Your GitHub organization or username, where this repository lives
repo: le-upptime # The name of this repository

sites:
  - name: me
    url: https://me.lei202.com
  - name: Leisskey(れいすきー)
    url: https://mk.lei202.com
  - name: lei202.com
    url: https://lei202.com
  - name: Blog
    url: https://blog.lei202.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lei202.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: lei202-Site-Upptime
  introTitle: "主にれいすきー用のUptimeサイト"
  introMessage: 試験運用中。なんか赤かったら落ちてます。
  navbar:
    - title: Status
      href: /
    - title: Leisskey
      href: https://mk.lei202.com
    - title: me
      href: https://me.lei202.com
    - title: Blog
      href: https://blog.lei202.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  allSystemsOperational: 全サイト正常稼働中。
  scheduledMaintenance: 予定されたメンテナンス
  liveStatus: 現在の稼働状況
  pastIncidents: 過去のインシデント
  overallUptime: "稼働率: $UPTIME"
  averageResponseTime: "平均応答時間: $TIMEms"
  averageResponseTimeTitle: 平均応答時間
  overallUptimeTitle: 稼働率
  sevelDayResponseTime: １週間の応答時間
